# Generated by Django 5.1.6 on 2025-02-23 01:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+6281212345678",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
